[program:frankenphp]
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
command=/usr/local/bin/frankenphp run --config /etc/caddy/Caddyfile
user=www-data

[program:queue_work]
numprocs=1
process_name=%(program_name)s_%(process_num)02d
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
command=/www/console queue:work
user=www-data
