[program:sse]
command=/usr/local/bin/php /opt/www/console sse:serve
directory=/opt/www
user=www-data
environment=OTEL_PHP_AUTOLOAD_ENABLED="false"
autorestart=true
startsecs=2
stopsignal=TERM
stopwaitsecs=10
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
